package com.jmp.sql.domain;

public class UserPoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point.id
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point.point_group
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    private String pointGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point.ponit_level
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    private String ponitLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point.point
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    private Integer point;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point.id
     *
     * @return the value of user_point.id
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point.id
     *
     * @param id the value for user_point.id
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point.point_group
     *
     * @return the value of user_point.point_group
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    public String getPointGroup() {
        return pointGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point.point_group
     *
     * @param pointGroup the value for user_point.point_group
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    public void setPointGroup(String pointGroup) {
        this.pointGroup = pointGroup == null ? null : pointGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point.ponit_level
     *
     * @return the value of user_point.ponit_level
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    public String getPonitLevel() {
        return ponitLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point.ponit_level
     *
     * @param ponitLevel the value for user_point.ponit_level
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    public void setPonitLevel(String ponitLevel) {
        this.ponitLevel = ponitLevel == null ? null : ponitLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point.point
     *
     * @return the value of user_point.point
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point.point
     *
     * @param point the value for user_point.point
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    public void setPoint(Integer point) {
        this.point = point;
    }
}