package com.jmp.sql.mapper;

import com.jmp.sql.domain.UserPoint;
import com.jmp.sql.domain.UserPointExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    int countByExample(UserPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    int deleteByExample(UserPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    int insert(UserPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    int insertSelective(UserPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    List<UserPoint> selectByExample(UserPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    UserPoint selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserPoint record, @Param("example") UserPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    int updateByExample(@Param("record") UserPoint record, @Param("example") UserPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    int updateByPrimaryKeySelective(UserPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_point
     *
     * @mbggenerated Wed Sep 19 15:48:53 CST 2018
     */
    int updateByPrimaryKey(UserPoint record);
}